export enum ModuleActionsEnum {
  UPDATE_USER_DATA = "USUARIOS - ACTUALIZAR DATOS DE USUARIO",
  BLOCK_USER = "USUARIOS - BLOQUEAR USUARIO",
  CREATE_PERMISSIONS = "PERMISOS - CREAR PERMISOS",
  UPDATE_PERMISSIONS = "PERMISOS - ACTUALIZAR PERMISOS",
  UPDATE_PASSWORD_POLICY = "POLÍTICA DE CONTRASEÑAS - ACTUALIZAR POLÍTICA DE CONTRASEÑAS",
  CREATE_APPS = "APLICACIONES Y MÓDULOS - CREAR APLICACIONES",
  CREATE_MODULES = "APLICACIONES Y MÓDULOS - CREAR MÓDULOS",
  CREATE_ACTIONS = "APLICACIONES Y MÓDULOS - CREAR ACCIONES",
}
