export enum IdType {
  CITIZENSHIP_CARD = "CÉDULA DE CIUDADANÍA",
  FOREIGNER_ID = "CÉDULA DE EXTRANJERÍA",
  IDENTITY_CARD = "TARJETA DE IDENTIDAD",
  CIVIL_REGISTRATION = "REGISTRO CIVIL",
  PASSPORT = "PASAPORTE",
  SPECIAL_RESIDENCE_PERMIT = "PERMISO ESPECIAL",
  TEMPORARY_PROTECTION_PERMIT = "PERMISO POR PROTECCIÓN TEMPORAL",
  DIPLOMATIC_CARD = "CARNET DIPLOMÁTICO",
  NIT = "NIT",
  PASS = "SALVOCONDUCTO",
  NOT_APPLICABLE = "NO APLICA",
}
