export const ImagesLinksApp = [
  "https://bonnadona-public.s3.amazonaws.com/assets/halcon.svg",
  "https://bonnadona-public.s3.amazonaws.com/assets/alicanto_logo.svg",
  "https://bonnadona-public.s3.amazonaws.com/assets/esparta.svg",
  "https://bonnadona-public.s3.amazonaws.com/assets/goodmed.svg",
  "https://bonnadona-public.s3.amazonaws.com/assets/magna_logo.svg",
  "https://hygea.s3.amazonaws.com/images/HYGEA.svg",
  "https://bonnadona-ethereum.s3.amazonaws.com/Images_project_templates/images_frontend/format_svg/Logo_Ethereum_Bonnadona_Hub.svg",
  "https://bonnadona-storage.s3.amazonaws.com/projects/hito/HITO-02.png",
  "https://bonnadona-storage.s3.amazonaws.com/projects/evaluacion-desempeno/profiles/Grupo+626.svg",
  "https://bonnadona-storage.s3.amazonaws.com/projects/aux_clinicos/Grupo+3525.png",
  "https://bonnadona-storage.s3.amazonaws.com/projects/exitus/EX1.png",
  "https://bonnadona-storage.s3.amazonaws.com/projects/caladrius/Logo+caladrius.png",
  "https://bonnadona-public.s3.amazonaws.com/assets/Cirugi%CC%81as1.png",
];
