export enum ActionTypesEnum {
  LOGIN = 'INICIO DE SESIÓN',
  CREATE_USER = 'CREAR USUARIO',
  UPDATE_DATA_USER = 'ACTUALIZACIÓN DATOS O ROLES DE USUARIO',
  UPDATE_DATA_USER_PROFILE = 'ACTUALIZACIÓN DATOS DE PERFIL DE USUARIO',
  BAN_USER = 'BANEAR USUARIO',
  UNBAN_USER = 'DESBANEAR USUARIO',
  UPDATE_PASSWORD_ACCOUNT = 'ACTUALIZACIÓN CONTRASEÑA CUENTA',
}
