export enum ModuleNameEnum {
  USER_MODULE = 'USUARIO',
  USER_PROFILE_MODULE = 'PERFIL DE USUARIO',
  ROLE_MODULE = 'ROLE',
  GENDERS_MODULE = 'GÉNEROS',
  ID_TYPES_MODULE = 'TIPOS DE IDENTIFICACIÓN',
  POSITION_LEVEL_MODULE = 'NIVELES DE CARGO',
  SERVICE_TYPES_MODULE = 'TIPOS DE SERVICIO',
}
