export enum IdTypeAbbrev {
  CÉDULA_DE_CIUDADANÍA = 'C',
  CÉDULA_DE_EXTRANJERÍA = 'E',
  TARJETA_DE_IDENTIDAD = 'T',
  REGISTRO_CIVIL = 'R',
  PASAPORTE = 'P',
  PERMISO_ESPECIAL = 'V',
  PERMISO_PROTECCIÓN_TEMPORAL = 'M',
  CARNET_DIPLOMÁTICO = 'D',
  NIT = 'N',
  SALVOCONDUCTO = 'S',
  NO_APLICA = 'F',
}
