export enum PositionLevelEnum {
  PRESIDENT = 'PRESIDENTE',
  MANAGER = 'GERENTE',
  DIRECTOR = 'DIRECTOR',
  COORDINATOR = 'COORDINADOR',
  BOSS = 'JEFE',
  DOCTOR = 'MÉDICO / ESPECIALISTA',
  ASSISTANT = 'AUXILIAR / ASISTENTE',
  APPRENTICE = 'APRENDIZ',
  AUDITOR = 'AUDITOR',
}
